import { Router } from "express";

import authMiddleware from "../middlewares/auth.middleware.js";
import { reports, summary } from "../controllers/insights.controller.js";

const router = Router();

// GET /insights/reports -> sales, inventory, expense, employee, customer
// and finance reports, all generated by @businessos/core from this
// business's live data.
router.get("/reports", authMiddleware, reports);

// GET /insights/summary -> plain-language business + inventory summaries
// generated by @businessos/core's ai module.
router.get("/summary", authMiddleware, summary);

export default router;
