import {
  generateSalesReport,
  generateInventoryReport,
  generateExpenseReport,
  generateEmployeeReport,
  generateCustomerReport,
  generateFinanceSnapshot,
  generateBusinessSummary,
  generateInventorySummary,
} from "@businessos/core";

import Product from "../models/product.model.js";
import Customer from "../models/customer.model.js";
import Employee from "../models/employee.model.js";
import Expense from "../models/expense.model.js";
import Order from "../models/order.model.js";

import {
  toCoreProducts,
  toCoreCustomers,
  toCoreEmployees,
  toCoreExpenses,
  toCoreOrders,
} from "../integrations/core.adapter.js";

/**
 * Loads every entity for this business and converts it to the plain
 * shapes business-core expects. Orders are populated with each line's
 * current product price so the adapter can approximate a unit price
 * (see core.adapter.ts for the caveat on historical accuracy).
 */
async function loadCoreData(businessId: string) {
  const [products, customers, employees, expenses, orders] = await Promise.all([
    Product.find({ businessId }),
    Customer.find({ businessId }),
    Employee.find({ businessId }),
    Expense.find({ businessId }),
    Order.find({ businessId }).populate("products.product", "price"),
  ]);

  return {
    coreProducts: toCoreProducts(products),
    coreCustomers: toCoreCustomers(customers),
    coreEmployees: toCoreEmployees(employees),
    coreExpenses: toCoreExpenses(expenses),
    coreOrders: toCoreOrders(orders),
  };
}

/**
 * Full structured report set — sales, inventory, expenses, employees,
 * customers and a finance snapshot — all generated by business-core's
 * reports module from this business's live MongoDB data.
 */
export const getFullReports = async (businessId: string) => {
  const { coreProducts, coreCustomers, coreEmployees, coreExpenses, coreOrders } =
    await loadCoreData(businessId);

  return {
    sales: generateSalesReport(coreOrders),
    inventory: generateInventoryReport(coreProducts),
    expenses: generateExpenseReport(coreExpenses),
    employees: generateEmployeeReport(coreEmployees),
    customers: generateCustomerReport(coreCustomers, coreOrders),
    finance: generateFinanceSnapshot(coreOrders, coreProducts, coreExpenses),
  };
};

/**
 * Plain-language business + inventory summaries produced by
 * business-core's "ai" module (data-shaping only, no external LLM call
 * yet — see business-core/src/ai/index.ts).
 */
export const getBusinessInsights = async (businessId: string) => {
  const { coreProducts, coreExpenses, coreOrders } = await loadCoreData(businessId);

  return {
    business: generateBusinessSummary(coreOrders, coreProducts, coreExpenses),
    inventory: generateInventorySummary(coreProducts),
  };
};
